AWSTemplateFormatVersion: 2010-09-09
Parameters:
  TwingateApiKey:
    Type: String
    Default: Insert Twingate API Key Here
  TwingateNetworkAddress:
    Type: String
    Default: Insert Twingate Network Address Here
Resources:
  TwingateAPIKeyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Twingate API Key
      Name: TwingateApiKey
      Type: String
      Value: !Ref TwingateApiKey
  TwingateNetworkAddressParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Twingate Network Address
      Name: TwingateNetworkAddress
      Type: String
      Value: !Ref TwingateNetworkAddress
  TwingateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: TwingateRole
      Policies:
        - PolicyName: EmbeddedInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DeleteTags"
                  - "ec2:CreateTags"
                  - "ec2:Describe*"
                  - "ecs:TagResource"
                  - "ecs:UntagResource"
                  - "ecs:Describe*"
                  - "rds:AddTagsToResource"
                  - "rds:RemoveTagsFromResource"
                  - "rds:Describe*"
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/ResourceGroupsandTagEditorFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      RoleName: !Join ["-", ["TwingateRole", !Ref "AWS::Region"]]
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        ImageUri: public.ecr.aws/p7x5l5b3/aws-tag-sync:latest
      Description: Lambda Function
      FunctionName: TgFunction
      Handler: app.handler
      MemorySize: 256
      PackageType: Zip
      Role: !GetAtt "TwingateRole.Arn"
      PackageType: image
      Runtime: nodejs14.x
      Timeout: 60
  LambdaAsyncconfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref LambdaFunction
      MaximumRetryAttempts: 0
      Qualifier: $LATEST
  CloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Cloud Watch Event Rule
      EventPattern: {"source":["aws.tag"],"detail-type":["Tag Change on Resource"],"detail":{"service":["ec2", "rds", "ecs"],"changed-tag-keys":["tg_resource","tg_groups", "tg_resource_id"]}}
      Name: TwingateTagWatch
      Targets:
        - Arn: !GetAtt "LambdaFunction.Arn"
          Id: WhatIsThis
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CloudWatchEventRule.Arn